sudo: false
matrix:
  fast_finish: true
  include:
    - python: "3.5"
      env: TOXENV=lint
    - python: "3.6"
      env: TOXENV=lint
    - python: "3.7"
      env: TOXENV=lint
      dist: xenial
install: pip install -U tox
language: python
script: tox
